### PR TITLE
Add support for RequireJS

### LINKED ISSUE #1: Ensure compatibility with RequireJS webapps
currently mocha.run() is called immediately, preventing any chance of loading up require modules & specs. This generator doesn't seem to have been updated to parity with the .9x release.

### PR DESCRIPTION
**Pull request by kevva**
Use the `--rjs` option to enable it. Fixes #1.

### CODE REVIEW

**Comment by arthurvr** [comment]
ping ;) Would love to have this in.

**Comment by SBoudrias** [comment]
Let's get it in!

**Comment by SBoudrias** [comment]
Actually, we'd need a rebase.

**Comment by kevva** [comment]
Yeah, I'll fix this tomorrow.

**Comment by arthurvr** [comment]
ping @kevva ;)

**Comment by arthurvr** [comment]
Yippee! Awesome @kevva

**Comment by kevva** [comment]
Maybe should change it to `--requirejs`?

**Pull request closed without merging**
