### PR TITLE
Adding prompt for DSL

### PR DESCRIPTION
**Pull request by revathskumar**

### CODE REVIEW

**Comment by arthurvr** [comment]
This will need a rebase, @revathskumar.

**Comment by SBoudrias** [comment]
@revathskumar just don't set a default to `--ui` if you'll prompt instead :wink:

**Comment by addyosmani** [comment]
I'm assuming that due to the age of this PR, we'll probably want to close it or re-explore via a larger rebase. Thoughts @revathskumar?

**Comment by eddiemonge** [comment]
I might have an update for this but waiting on my other two PRs first

**Comment by eddiemonge** [comment]
Closing in favor of https://github.com/yeoman/generator-mocha/pull/39

**Pull request closed without merging**
